version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/build/docker/alpine"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/build/docker/slim"
    schedule:
      interval: "weekly"
