version: 2
registries:
  dhi-registry:
    type: docker-registry
    url: https://dhi.io
    username: ${{secrets.DOCKER_HUB_USERNAME}}
    password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/build/docker/alpine"
    registries:
      - dhi-registry
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/build/docker/slim"
    registries:
      - dhi-registry
    schedule:
      interval: "weekly"
