version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/alpine"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/slim"
    schedule:
      interval: "weekly"
