---
version: "2"
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
    - govet
    - revive
  settings:
    gocyclo:
      min-complexity: 15
run:
  timeout: 5m
