---
version: "2"
formatters:
  enable:
    - goimports
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - gocritic
    - govet
    - revive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst
  settings:
    gocyclo:
      min-complexity: 15
run:
  timeout: 5m
