---
name: "Lint Code Base"
on:
  push:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

permissions: {}

jobs:
  lint:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: cat .github/super-linter.env >> "$GITHUB_ENV"
      - uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ github.token }}
