---
name: plantuml
on:
  push:
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]

permissions: {}

jobs:
  plantuml:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker://plantuml/plantuml:1.2025.4
        env:
          GIT_REPO_URL: ${{ github.server_url }}/${{ github.repository }}/
        with:
          args: "-v -o /github/workspace/_site docs/"
      - uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: plantuml
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      actions: read
      contents: read
      id-token: write
      pages: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
