on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - run: make test
    - name: Convert coverage file
      if: "matrix.platform == 'ubuntu-latest'"
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
        infile: coverage.out
        outfile: coverage.lcov
    - name: Send coverage
      if: "matrix.platform == 'ubuntu-latest'"
      uses: coverallsapp/github-action@v1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
        flag-name: ${{matrix.go-version}}-node-${{ matrix.platform }}
