on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: make test
    - name: convert coverage file
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
        infile: coverage.out
        outfile: coverage.lcov
    - name: Send coverage
      if: "matrix.platform == 'ubuntu-latest'"
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.coveralls_io }}
        path-to-lcov: coverage.lcov
